name: Build and deploy OpenSPP documentation

on:
  push:
    branches:
      - "main"

  schedule:
    # First day of month at 05:46 in every 2nd month
    - cron: '46 5 * * 1'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          sudo apt-get install libsasl2-dev libldap2-dev libssl-dev &&
          pip install -q -r requirements_frozen.txt

      - name: Run linkcheck
        run: make linkcheck
