name: Get latest version of submodules and push back to docs_v3 branch

on:
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with: 
          ref: master
          submodules: true

      - name: Submodule update
        run: |
          git status
          git submodule update --init --recursive
          git submodule update --remote --recursive

      - name: Commit updates
        run: |
          git status
          git add submodules/openg2p-program submodules/openg2p-registry
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Update submodules tip" || echo "No changes to commit"
          git push
